# ??
server:
  port: 8002

# ????
spring:
  application:
    name: service-apis


  cloud:
    nacos:
      discovery:
        # ??????
        server-addr: localhost:8848
        # ???
        username: nacos
        # ??
        password: nacos

        # ????????????????
        namespace: public


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/network?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: chen

  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#
#management:
#  endpoint:
#    web:
#      exposure:
#        enabled:

feign:
  hystrix:
    enabled: true


